const THEME = {
    ltr: 'ltr',
    rtl: 'rtl',
    paragraph: 'editor-paragraph',
    quote: 'editor-quote',
    heading: {
      h1: 'editor-heading-h1',
      h2: 'editor-heading-h2',
      h3: 'editor-heading-h3',
      h4: 'editor-heading-h4',
      h5: 'editor-heading-h5',
      h6: 'editor-heading-h6',
    },
    list: {
      nested: {
        listitem: 'editor-nested-listitem',
      },
      ol: 'editor-list-ol',
      ul: 'editor-list-ul',
      listitem: 'editor-listItem',
      listitemChecked: 'editor-listItemChecked',
      listitemUnchecked: 'editor-listItemUnchecked',
    },
    hashtag: 'editor-hashtag',
    image: 'editor-image',
    link: 'editor-link',
    text: {
      bold: 'editor-textBold',
      code: 'editor-textCode',
      italic: 'editor-textItalic',
      strikethrough: 'editor-textStrikethrough',
      subscript: 'editor-textSubscript',
      superscript: 'editor-textSuperscript',
      underline: 'editor-textUnderline',
      underlineStrikethrough: 'editor-textUnderlineStrikethrough',
    },
    code: 'editor-code',
    codeHighlight: {
      atrule: 'prism_atrule',
      attr: 'prism_attr',
      boolean: 'prism_boolean',
      builtin: 'prism_builtin',
      cdata: 'prism_cdata',
      char: 'prism_cdata',
      class: 'prism_class',
      'class-name': 'prism_class_name',
      comment: 'prism_comment',
      constant: 'prism_constant',
      deleted: 'prism_deleted',
      doctype: 'prism_doctype',
      entity: 'prism_entity',
      "function": 'prism_function',
      important: 'prism_important',
      inserted: 'prism_inserted',
      keyword: 'prism_keyword',
      namespace: 'prism_namespace',
      number: 'prism_number',
      operator: 'prism_operator',
      prolog: 'prism_prolog',
      property: 'prism_property',
      punctuation: 'prism_punctuation',
      regex: 'prism_regex',
      selector: 'prism_selector',
      string: 'prism_string',
      symbol: 'prism_symbol',
      tag: 'prism_tag',
      url: 'prism_url',
      variable: 'prism_variable',
    },
  };

export default THEME